version: "3.3"

services:
  people-blazorwasmserver:
    build:
      context: .
      dockerfile: ./src/People.BlazorWasmServer/Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
