# fly.toml app configuration file generated for blazor-wasm-crud on 2023-11-20T13:51:01-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "blazor-wasm-crud"
primary_region = "iad"

[build]
  dockerfile = "./src/People.BlazorWasmServer/Dockerfile"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
